"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlanErrorNotice = exports.TemporalSensitivityTable = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const lucide_react_1 = require("lucide-react");
const bloc1TemporalUi_1 = require("./bloc1TemporalUi");
const TemporalSensitivityTable = () => {
    const t = bloc1TemporalUi_1.TEMPORAL_SENSITIVITY;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "space-y-3", id: "temporal-sensitivity", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-sm font-bold text-gray-800", children: "Sensibilit\u00E9 de la couverture de stock" }), (0, jsx_runtime_1.jsxs)("div", { className: "p-3 bg-amber-50 border border-amber-300 rounded-lg text-xs text-amber-950 leading-relaxed space-y-1", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-1.5 font-bold", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.TriangleAlert, { size: 14, className: "shrink-0" }), " Une couverture trop faible peut rendre un sc\u00E9nario impossible \u00E0 calibrer"] }), (0, jsx_runtime_1.jsx)("p", { children: "Pour garantir un IP \u00E9gal \u00E0 1 avant la perturbation malgr\u00E9 le bruit de demande, le moteur cherche une demande de r\u00E9f\u00E9rence que le r\u00E9seau sert int\u00E9gralement pendant la chauffe. Avec trop peu de stock au regard du bruit et des d\u00E9lais, aucune demande ne convient : le plan est alors refus\u00E9, avec le sc\u00E9nario en cause et le rem\u00E8de. Plus la couverture est forte, moins les pannes courtes produisent de creux d'IP : \u00E0 choisir selon l'\u00E9tude." })] }), (0, jsx_runtime_1.jsx)("div", { className: "overflow-x-auto border border-gray-200 rounded-lg bg-white", children: (0, jsx_runtime_1.jsxs)("table", { className: "w-full text-xs", children: [(0, jsx_runtime_1.jsx)("thead", { className: "bg-gray-50 text-gray-700", children: (0, jsx_runtime_1.jsxs)("tr", { children: [(0, jsx_runtime_1.jsx)("th", { className: "text-left px-3 py-2 font-semibold", children: "Couverture (s / S)" }), (0, jsx_runtime_1.jsx)("th", { className: "text-left px-3 py-2 font-semibold", children: "Pannes avec creux d'IP" }), (0, jsx_runtime_1.jsx)("th", { className: "text-left px-3 py-2 font-semibold", children: "Remarque" })] }) }), (0, jsx_runtime_1.jsxs)("tbody", { children: [(0, jsx_runtime_1.jsxs)("tr", { className: "border-t border-gray-100 text-gray-600", children: [(0, jsx_runtime_1.jsx)("td", { className: "px-3 py-1.5", children: t.baseline.label }), (0, jsx_runtime_1.jsxs)("td", { className: "px-3 py-1.5", children: [t.baseline.dips, " sur ", t.baseline.of] }), (0, jsx_runtime_1.jsx)("td", { className: "px-3 py-1.5", children: "R\u00E9f\u00E9rence : sans stock ni d\u00E9lai" })] }), t.coverage.map(row => ((0, jsx_runtime_1.jsxs)("tr", { className: `border-t border-gray-100 ${row.status === 'refused' ? 'bg-red-50 text-red-900' : ''}`, children: [(0, jsx_runtime_1.jsx)("td", { className: "px-3 py-1.5 font-medium", children: row.label }), (0, jsx_runtime_1.jsx)("td", { className: "px-3 py-1.5", children: row.status === 'ok' ? `${row.dips} sur ${row.of}` : `Plan refusé (scénario ${row.refusedAt})` }), (0, jsx_runtime_1.jsx)("td", { className: "px-3 py-1.5", children: row.status === 'ok'
                                                ? (row.dips === 0 ? 'Pannes de 3 à 15 jours entièrement absorbées' : 'Creux surtout sur les pannes longues et sévères')
                                                : `Calibration impossible pour ${row.refusedAt} ; ${row.dips} sur ${row.of} avec creux parmi les scénarios précédents` })] }, row.label)))] })] }) }), (0, jsx_runtime_1.jsx)("div", { className: "overflow-x-auto border border-gray-200 rounded-lg bg-white", children: (0, jsx_runtime_1.jsxs)("table", { className: "w-full text-xs", children: [(0, jsx_runtime_1.jsx)("thead", { className: "bg-gray-50 text-gray-700", children: (0, jsx_runtime_1.jsxs)("tr", { children: [(0, jsx_runtime_1.jsx)("th", { className: "text-left px-3 py-2 font-semibold", children: "Couverture par d\u00E9faut (3 / 10 jours), dur\u00E9e des pannes" }), (0, jsx_runtime_1.jsx)("th", { className: "text-left px-3 py-2 font-semibold", children: "Pannes avec creux d'IP" })] }) }), (0, jsx_runtime_1.jsx)("tbody", { children: t.durations.map(row => ((0, jsx_runtime_1.jsxs)("tr", { className: "border-t border-gray-100", children: [(0, jsx_runtime_1.jsx)("td", { className: "px-3 py-1.5", children: row.range }), (0, jsx_runtime_1.jsxs)("td", { className: "px-3 py-1.5", children: [row.dips, " sur ", row.of] })] }, row.range))) })] }) }), (0, jsx_runtime_1.jsxs)("p", { className: "text-[11px] text-gray-500 leading-relaxed", children: ["Mesures fig\u00E9es, produites dans les conditions suivantes : ", t.conditions, ". Elles valent pour cet \u00E9chantillon (une graine) et ne se transposent pas telles quelles \u00E0 un autre r\u00E9seau : refaire un petit lot d'essai pour votre r\u00E9seau avant une \u00E9tude."] })] }));
};
exports.TemporalSensitivityTable = TemporalSensitivityTable;
// Affichage d'un refus de plan. Une erreur sans détail structuré garde
// exactement l'affichage d'origine (bandeau rouge d'une ligne).
const PlanErrorNotice = ({ view, onOpenTemporalSettings }) => {
    if (view.kind === 'other') {
        return ((0, jsx_runtime_1.jsxs)("div", { className: "mt-3 p-3 bg-red-100 text-red-800 rounded-lg text-sm flex items-center gap-2", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertCircle, { size: 18 }), " ", view.message] }));
    }
    return ((0, jsx_runtime_1.jsxs)("div", { className: "mt-3 p-4 bg-red-50 border border-red-300 rounded-lg text-sm text-red-900 space-y-2", role: "alert", children: [(0, jsx_runtime_1.jsxs)("div", { className: "flex items-center gap-2 font-bold", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.AlertCircle, { size: 18, className: "shrink-0" }), " ", view.title] }), view.details && ((0, jsx_runtime_1.jsx)("ul", { className: "list-disc list-inside space-y-0.5 text-xs", children: view.details.map((d, i) => (0, jsx_runtime_1.jsx)("li", { children: d }, i)) })), view.remedy && (0, jsx_runtime_1.jsxs)("p", { className: "text-xs font-semibold", children: ["Rem\u00E8de : ", view.remedy] }), onOpenTemporalSettings && ((0, jsx_runtime_1.jsxs)("button", { type: "button", onClick: onOpenTemporalSettings, className: "px-3 py-1.5 bg-white hover:bg-red-100 text-red-800 rounded-md text-xs font-semibold border border-red-300 flex items-center gap-1.5", children: [(0, jsx_runtime_1.jsx)(lucide_react_1.Settings, { size: 13 }), " Ouvrir les r\u00E9glages du mode temporel"] }))] }));
};
exports.PlanErrorNotice = PlanErrorNotice;
